"""add weekly goal habit and target

Revision ID: 78f764046e7d
Revises: fc024d63765f
Create Date: 2026-09-18 05:17:46.975240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78f764046e7d'
down_revision: Union[str, None] = 'fc024d63765f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weekly_goals', sa.Column('habit_id', sa.Integer(), nullable=True))
    op.add_column('weekly_goals', sa.Column('target_count', sa.Integer(), nullable=True))
    op.create_foreign_key('weekly_goals_habit_id_fkey', 'weekly_goals', 'habits', ['habit_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('weekly_goals_habit_id_fkey', 'weekly_goals', type_='foreignkey')
    op.drop_column('weekly_goals', 'target_count')
    op.drop_column('weekly_goals', 'habit_id')
    # ### end Alembic commands ###
