"""add milestone position

Revision ID: 7fe27842b9ef
Revises: 78f764046e7d
Create Date: 2026-09-18 19:46:17.150626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fe27842b9ef'
down_revision: Union[str, None] = '78f764046e7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milestones', sa.Column('position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('milestones', 'position')
    # ### end Alembic commands ###
