"""add weekly_reviews; derive task priority

Revision ID: bc5df8360f9e
Revises: 7fe27842b9ef
Create Date: 2026-09-21 12:14:35.414539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc5df8360f9e'
down_revision: Union[str, None] = '7fe27842b9ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('achieved_count', sa.Integer(), nullable=False),
    sa.Column('measurable_count', sa.Integer(), nullable=False),
    sa.Column('unplanned_count', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_reviews_week_start'), 'weekly_reviews', ['week_start'], unique=True)
    # ### end Alembic commands ###

    # Task.priority is now derived from (importance, urgency) by
    # tools.tasks.derive_priority. Backfill existing rows so none is left with a
    # stale hand-set value; keep this CASE in step with that function.
    op.execute(
        """
        UPDATE tasks SET priority = (CASE
            WHEN importance IS NULL OR urgency IS NULL THEN 'MEDIUM'
            WHEN importance >= 3 AND urgency >= 3 THEN 'URGENT'
            WHEN importance >= 3 THEN 'HIGH'
            WHEN urgency >= 3 THEN 'MEDIUM'
            ELSE 'LOW'
        END)::task_priority
        """
    )


def downgrade() -> None:
    # The priority backfill has no inverse: the pre-backfill values weren't
    # recorded anywhere, and nothing read them.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_reviews_week_start'), table_name='weekly_reviews')
    op.drop_table('weekly_reviews')
    # ### end Alembic commands ###
