"""add task importance urgency

Revision ID: fc024d63765f
Revises: 89e2870d539b
Create Date: 2026-08-18 00:06:29.019844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc024d63765f'
down_revision: Union[str, None] = '89e2870d539b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('importance', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('urgency', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'urgency')
    op.drop_column('tasks', 'importance')
    # ### end Alembic commands ###
